<?php
/**
 * language.php — Strings de interfaz en múltiples idiomas
 * Idiomas disponibles: es | en | fr | de | ru
 */

$LANG = [
    // ── ESPAÑOL ─────────────────────────────────────────────────
    'es' => [
        'site_title'            => 'Migrador — AzerothCore',
        'app_name'              => 'Migrador AC',
        'login_title'           => 'Acceder',
        'login_user'            => 'Usuario',
        'login_pass'            => 'Contraseña',
        'login_btn'             => 'Entrar',
        'login_footer'          => 'Usa las mismas credenciales del juego.',
        'login_error'           => 'Usuario o contraseña incorrectos.',
        'login_locked'          => 'Esta cuenta está bloqueada.',
        'login_rate_limited'    => 'Demasiados intentos fallidos. Inténtalo de nuevo en unos minutos.',
        'logout'                => 'Cerrar sesión',
        'welcome'               => 'Bienvenido',

        'transfer_title'        => 'Transferencia de Personaje',
        'transfer_step1'        => 'Paso 1 — Subir dump de personaje',
        'transfer_step2'        => 'Paso 2 — Confirmar nombre del personaje',
        'transfer_status_0'     => 'En progreso',
        'transfer_status_1'     => 'Aprobado',
        'transfer_status_2'     => 'Denegado',
        'transfer_status_3'     => 'Cancelado',
        'transfer_status_4'     => 'Reenviado',

        'btn_approve'           => 'Aprobar',
        'btn_deny'              => 'Denegar',
        'btn_resend'            => 'Reenviar',
        'btn_cancel'            => 'Cancelar',
        'btn_submit'            => 'Enviar',
        'btn_upload'            => 'Subir archivo',
        'btn_confirm'           => 'Confirmar',
        'btn_back'              => '← Volver',

        'gm_panel'              => 'Panel de Administración',
        'player_panel'          => 'Mis Transferencias',

        'char_online_error'     => 'El personaje debe estar desconectado.',
        'transfer_not_pending'  => 'Esta transferencia no está en estado pendiente.',
        'access_denied'         => 'Acceso denegado.',
        'server_offline'        => 'El servidor está offline en este momento.',
        'invalid_file'          => 'Archivo inválido. Solo se acepta chardump.lua generado por el addon.',
        'invalid_char_name'     => 'Nombre inválido (solo letras, 2-16 caracteres).',
        'name_taken'            => 'Ese nombre de personaje ya está en uso en este servidor.',
        'transfer_queued'       => '✔ Tu transferencia ha sido registrada y está en revisión. Un GM la procesará pronto.',
        'transfer_cancelled'    => 'Transferencia cancelada correctamente.',
        'transfer_approved'     => '✔ Transferencia aprobada. El personaje ha sido asignado a tu cuenta.',
        'transfer_denied'       => 'Transferencia denegada.',
        'achievement_fail'      => 'Tu personaje no cumple el mínimo de logros requerido (' . MIN_ACHIEVEMENTS . ').',
        'level_fail'            => 'El nivel del personaje supera el máximo permitido (' . MAX_LEVEL . ').',
        'blacklisted'           => 'Tu cuenta está en la lista negra de transferencias.',
        'invalid_dump'          => 'El dump de personaje no es válido o está corrupto.',
        'dump_apply_error'      => 'Error al aplicar el dump en la base de datos. Contacta a un administrador.',
        'reason_label'          => 'Motivo',
        'no_transfers'          => 'No hay transferencias registradas.',

        'instructions_title'    => 'Cómo transferir tu personaje',
        'instructions'          => '<ol>
            <li>En el servidor de <strong>origen</strong>, instala el addon <code>chardump</code>.</li>
            <li>Entra al juego y escribe <code>/chardump</code> — se generará el archivo.</li>
            <li>Localiza el archivo <code>chardump.lua</code> en tu carpeta WTF del cliente.</li>
            <li>Sube ese archivo aquí usando el botón de abajo.</li>
            <li>Un GM revisará tu solicitud en un plazo de 24-48 horas.</li>
            <li>Recibirás notificación cuando el personaje esté listo.</li>
        </ol>',

        'realm_select'          => 'Realm destino',
        'select_realm'          => '— Selecciona un realm —',
        'upload_label'          => 'Archivo chardump.lua',
        'char_name_label'       => 'Nombre del personaje en este servidor',
        'char_name_hint'        => 'Solo letras, 2-16 caracteres. Sin espacios ni números.',
        'confirm_cancel'        => '¿Confirmas la cancelación de esta transferencia?',
        'confirm_approve'       => '¿Aprobar esta transferencia?',
        'confirm_deny'          => '¿Denegar esta transferencia?',
        'deny_reason'           => 'Motivo de denegación',
        'items_sent'            => 'Los items han sido reenviados por correo en el juego.',
        'token_error'           => 'Error de seguridad. Recarga la página e inténtalo de nuevo.',
    ],

    // ── ENGLISH ─────────────────────────────────────────────────
    'en' => [
        'site_title'            => 'Migrator — AzerothCore',
        'app_name'              => 'AC Migrator',
        'login_title'           => 'Login',
        'login_user'            => 'Username',
        'login_pass'            => 'Password',
        'login_btn'             => 'Sign In',
        'login_footer'          => 'Use the same credentials as the game.',
        'login_error'           => 'Wrong username or password.',
        'login_locked'          => 'This account is locked.',
        'login_rate_limited'    => 'Too many failed attempts. Try again in a few minutes.',
        'logout'                => 'Logout',
        'welcome'               => 'Welcome',

        'transfer_title'        => 'Character Transfer',
        'transfer_step1'        => 'Step 1 — Upload character dump',
        'transfer_step2'        => 'Step 2 — Confirm character name',
        'transfer_status_0'     => 'In Progress',
        'transfer_status_1'     => 'Approved',
        'transfer_status_2'     => 'Denied',
        'transfer_status_3'     => 'Cancelled',
        'transfer_status_4'     => 'Resent',

        'btn_approve'           => 'Approve',
        'btn_deny'              => 'Deny',
        'btn_resend'            => 'Resend',
        'btn_cancel'            => 'Cancel',
        'btn_submit'            => 'Submit',
        'btn_upload'            => 'Upload File',
        'btn_confirm'           => 'Confirm',
        'btn_back'              => '← Back',

        'gm_panel'              => 'Admin Panel',
        'player_panel'          => 'My Transfers',

        'char_online_error'     => 'Character must be offline.',
        'transfer_not_pending'  => 'Transfer is not in a pending state.',
        'access_denied'         => 'Access denied.',
        'server_offline'        => 'The server is currently offline.',
        'invalid_file'          => 'Invalid file. Only chardump.lua from the addon is accepted.',
        'invalid_char_name'     => 'Invalid name (letters only, 2-16 chars).',
        'name_taken'            => 'That character name is already taken on this server.',
        'transfer_queued'       => '✔ Your transfer has been queued. A GM will review it soon.',
        'transfer_cancelled'    => 'Transfer cancelled.',
        'transfer_approved'     => '✔ Transfer approved. Character assigned to your account.',
        'transfer_denied'       => 'Transfer denied.',
        'achievement_fail'      => 'Character does not meet the minimum achievement requirement (' . MIN_ACHIEVEMENTS . ').',
        'level_fail'            => 'Character level exceeds the allowed maximum (' . MAX_LEVEL . ').',
        'blacklisted'           => 'Your account is blacklisted from transfers.',
        'invalid_dump'          => 'Invalid or corrupted character dump.',
        'dump_apply_error'      => 'Failed to apply dump. Please contact an administrator.',
        'reason_label'          => 'Reason',
        'no_transfers'          => 'No transfers found.',

        'instructions_title'    => 'How to transfer your character',
        'instructions'          => '<ol>
            <li>On the <strong>source</strong> server, install the <code>chardump</code> addon.</li>
            <li>Log in and type <code>/chardump</code> — a file will be generated.</li>
            <li>Find <code>chardump.lua</code> in your WTF folder.</li>
            <li>Upload it here using the button below.</li>
            <li>A GM will review your request within 24-48 hours.</li>
            <li>You will be notified once the character is ready.</li>
        </ol>',

        'realm_select'          => 'Destination Realm',
        'select_realm'          => '— Select a realm —',
        'upload_label'          => 'chardump.lua file',
        'char_name_label'       => 'Character name on this server',
        'char_name_hint'        => 'Letters only, 2-16 characters. No spaces or numbers.',
        'confirm_cancel'        => 'Confirm cancellation of this transfer?',
        'confirm_approve'       => 'Approve this transfer?',
        'confirm_deny'          => 'Deny this transfer?',
        'deny_reason'           => 'Denial reason',
        'items_sent'            => 'Items have been resent via in-game mail.',
        'token_error'           => 'Security error. Reload the page and try again.',
    ],

    // ── FRANÇAIS ────────────────────────────────────────────────
    'fr' => [
        'site_title'            => 'Migrateur — AzerothCore',
        'app_name'              => 'Migrateur AC',
        'login_title'           => 'Connexion',
        'login_user'            => 'Utilisateur',
        'login_pass'            => 'Mot de passe',
        'login_btn'             => 'Se connecter',
        'login_footer'          => 'Utilisez les mêmes identifiants que dans le jeu.',
        'login_error'           => 'Nom d\'utilisateur ou mot de passe incorrect.',
        'login_locked'          => 'Ce compte est verrouillé.',
        'login_rate_limited'    => 'Trop de tentatives échouées. Réessayez dans quelques minutes.',
        'logout'                => 'Déconnexion',
        'welcome'               => 'Bienvenue',
        'transfer_title'        => 'Transfert de personnage',
        'transfer_step1'        => 'Étape 1 — Télécharger le dump',
        'transfer_step2'        => 'Étape 2 — Confirmer le nom',
        'transfer_status_0'     => 'En cours',
        'transfer_status_1'     => 'Approuvé',
        'transfer_status_2'     => 'Refusé',
        'transfer_status_3'     => 'Annulé',
        'transfer_status_4'     => 'Renvoyé',
        'btn_approve'           => 'Approuver',
        'btn_deny'              => 'Refuser',
        'btn_resend'            => 'Renvoyer',
        'btn_cancel'            => 'Annuler',
        'btn_submit'            => 'Envoyer',
        'btn_upload'            => 'Télécharger',
        'btn_confirm'           => 'Confirmer',
        'btn_back'              => '← Retour',
        'gm_panel'              => 'Panneau Admin',
        'player_panel'          => 'Mes transferts',
        'no_transfers'          => 'Aucun transfert trouvé.',
        'access_denied'         => 'Accès refusé.',
        'server_offline'        => 'Le serveur est hors ligne.',
        'invalid_file'          => 'Fichier invalide.',
        'invalid_char_name'     => 'Nom invalide (lettres uniquement, 2-16 chars).',
        'name_taken'            => 'Ce nom de personnage est déjà utilisé.',
        'transfer_queued'       => '✔ Votre transfert a été enregistré.',
        'transfer_cancelled'    => 'Transfert annulé.',
        'transfer_approved'     => '✔ Transfert approuvé.',
        'transfer_denied'       => 'Transfert refusé.',
        'achievement_fail'      => 'Succès insuffisants (' . MIN_ACHIEVEMENTS . ' requis).',
        'level_fail'            => 'Niveau trop élevé (max ' . MAX_LEVEL . ').',
        'blacklisted'           => 'Compte sur liste noire.',
        'invalid_dump'          => 'Dump invalide.',
        'dump_apply_error'      => 'Erreur lors de l\'application du dump.',
        'instructions_title'    => 'Comment transférer',
        'instructions'          => 'Installez l\'addon <code>chardump</code>, tapez <code>/chardump</code> en jeu, puis téléchargez le fichier ici.',
        'realm_select'          => 'Realm de destination',
        'select_realm'          => '— Choisir un realm —',
        'upload_label'          => 'Fichier chardump.lua',
        'char_name_label'       => 'Nom du personnage',
        'char_name_hint'        => 'Lettres uniquement, 2-16 caractères.',
        'confirm_cancel'        => 'Confirmer l\'annulation ?',
        'confirm_approve'       => 'Approuver ce transfert ?',
        'confirm_deny'          => 'Refuser ce transfert ?',
        'deny_reason'           => 'Motif',
        'items_sent'            => 'Objets renvoyés par courrier en jeu.',
        'token_error'           => 'Erreur de sécurité. Rechargez la page.',
        'char_online_error'     => 'Le personnage doit être hors ligne.',
        'transfer_not_pending'  => 'Ce transfert n\'est pas en attente.',
        'reason_label'          => 'Motif',
    ],

    // ── DEUTSCH ─────────────────────────────────────────────────
    'de' => [
        'site_title'            => 'Migrator — AzerothCore',
        'app_name'              => 'AC Migrator',
        'login_title'           => 'Anmelden',
        'login_user'            => 'Benutzername',
        'login_pass'            => 'Passwort',
        'login_btn'             => 'Einloggen',
        'login_footer'          => 'Verwende dieselben Zugangsdaten wie im Spiel.',
        'login_error'           => 'Falscher Benutzername oder Passwort.',
        'login_locked'          => 'Dieses Konto ist gesperrt.',
        'login_rate_limited'    => 'Zu viele fehlgeschlagene Versuche. Versuche es in ein paar Minuten erneut.',
        'logout'                => 'Abmelden',
        'welcome'               => 'Willkommen',
        'transfer_title'        => 'Charaktertransfer',
        'transfer_step1'        => 'Schritt 1 — Dump hochladen',
        'transfer_step2'        => 'Schritt 2 — Namen bestätigen',
        'transfer_status_0'     => 'In Bearbeitung',
        'transfer_status_1'     => 'Genehmigt',
        'transfer_status_2'     => 'Abgelehnt',
        'transfer_status_3'     => 'Storniert',
        'transfer_status_4'     => 'Erneut gesendet',
        'btn_approve'           => 'Genehmigen',
        'btn_deny'              => 'Ablehnen',
        'btn_resend'            => 'Erneut senden',
        'btn_cancel'            => 'Abbrechen',
        'btn_submit'            => 'Absenden',
        'btn_upload'            => 'Datei hochladen',
        'btn_confirm'           => 'Bestätigen',
        'btn_back'              => '← Zurück',
        'gm_panel'              => 'Admin-Bereich',
        'player_panel'          => 'Meine Transfers',
        'no_transfers'          => 'Keine Transfers gefunden.',
        'access_denied'         => 'Zugriff verweigert.',
        'server_offline'        => 'Der Server ist derzeit offline.',
        'invalid_file'          => 'Ungültige Datei. Nur chardump.lua vom Addon wird akzeptiert.',
        'invalid_char_name'     => 'Ungültiger Name (nur Buchstaben, 2-16 Zeichen).',
        'name_taken'            => 'Dieser Charaktername wird bereits verwendet.',
        'transfer_queued'       => '✔ Dein Transfer wurde eingereicht. Ein GM wird ihn bald prüfen.',
        'transfer_cancelled'    => 'Transfer storniert.',
        'transfer_approved'     => '✔ Transfer genehmigt. Der Charakter wurde deinem Konto zugewiesen.',
        'transfer_denied'       => 'Transfer abgelehnt.',
        'achievement_fail'      => 'Charakter erfüllt nicht die Mindestanzahl an Erfolgen (' . MIN_ACHIEVEMENTS . ').',
        'level_fail'            => 'Charakterstufe überschreitet das erlaubte Maximum (' . MAX_LEVEL . ').',
        'blacklisted'           => 'Dein Konto ist für Transfers gesperrt.',
        'invalid_dump'          => 'Ungültiger oder beschädigter Charakter-Dump.',
        'dump_apply_error'      => 'Fehler beim Anwenden des Dumps. Bitte kontaktiere einen Administrator.',
        'reason_label'          => 'Grund',
        'instructions_title'    => 'So transferierst du deinen Charakter',
        'instructions'          => '<ol>
            <li>Installiere auf dem <strong>Quellserver</strong> das Addon <code>chardump</code>.</li>
            <li>Logge dich ein und gib <code>/chardump</code> ein — eine Datei wird erzeugt.</li>
            <li>Finde <code>chardump.lua</code> in deinem WTF-Ordner.</li>
            <li>Lade sie hier über den Button unten hoch.</li>
            <li>Ein GM prüft deine Anfrage innerhalb von 24-48 Stunden.</li>
            <li>Du wirst benachrichtigt, sobald der Charakter bereit ist.</li>
        </ol>',
        'realm_select'          => 'Ziel-Realm',
        'select_realm'          => '— Realm auswählen —',
        'upload_label'          => 'chardump.lua-Datei',
        'char_name_label'       => 'Charaktername auf diesem Server',
        'char_name_hint'        => 'Nur Buchstaben, 2-16 Zeichen. Keine Leerzeichen oder Zahlen.',
        'confirm_cancel'        => 'Stornierung dieses Transfers bestätigen?',
        'confirm_approve'       => 'Diesen Transfer genehmigen?',
        'confirm_deny'          => 'Diesen Transfer ablehnen?',
        'deny_reason'           => 'Ablehnungsgrund',
        'items_sent'            => 'Gegenstände wurden erneut per Ingame-Post gesendet.',
        'token_error'           => 'Sicherheitsfehler. Lade die Seite neu und versuche es erneut.',
        'char_online_error'     => 'Der Charakter muss offline sein.',
        'transfer_not_pending'  => 'Dieser Transfer ist nicht in Bearbeitung.',
    ],

    // ── РУССКИЙ ─────────────────────────────────────────────────
    'ru' => [
        'site_title'            => 'Мигратор — AzerothCore',
        'app_name'              => 'Мигратор AC',
        'login_title'           => 'Вход',
        'login_user'            => 'Имя пользователя',
        'login_pass'            => 'Пароль',
        'login_btn'             => 'Войти',
        'login_footer'          => 'Используйте те же учетные данные, что и в игре.',
        'login_error'           => 'Неверное имя пользователя или пароль.',
        'login_locked'          => 'Эта учётная запись заблокирована.',
        'login_rate_limited'    => 'Слишком много неудачных попыток. Повторите через несколько минут.',
        'logout'                => 'Выйти',
        'welcome'               => 'Добро пожаловать',
        'transfer_title'        => 'Перенос персонажа',
        'transfer_step1'        => 'Шаг 1 — Загрузить дамп персонажа',
        'transfer_step2'        => 'Шаг 2 — Подтвердить имя персонажа',
        'transfer_status_0'     => 'В процессе',
        'transfer_status_1'     => 'Одобрено',
        'transfer_status_2'     => 'Отклонено',
        'transfer_status_3'     => 'Отменено',
        'transfer_status_4'     => 'Отправлено повторно',
        'btn_approve'           => 'Одобрить',
        'btn_deny'              => 'Отклонить',
        'btn_resend'            => 'Отправить снова',
        'btn_cancel'            => 'Отменить',
        'btn_submit'            => 'Отправить',
        'btn_upload'            => 'Загрузить файл',
        'btn_confirm'           => 'Подтвердить',
        'btn_back'              => '← Назад',
        'gm_panel'              => 'Панель администратора',
        'player_panel'          => 'Мои переносы',
        'no_transfers'          => 'Переносы не найдены.',
        'access_denied'         => 'Доступ запрещён.',
        'server_offline'        => 'Сервер сейчас недоступен.',
        'invalid_file'          => 'Неверный файл. Принимается только chardump.lua от аддона.',
        'invalid_char_name'     => 'Неверное имя (только буквы, 2-16 символов).',
        'name_taken'            => 'Это имя персонажа уже занято на этом сервере.',
        'transfer_queued'       => '✔ Ваш перенос поставлен в очередь. GM скоро его рассмотрит.',
        'transfer_cancelled'    => 'Перенос отменён.',
        'transfer_approved'     => '✔ Перенос одобрен. Персонаж привязан к вашей учётной записи.',
        'transfer_denied'       => 'Перенос отклонён.',
        'achievement_fail'      => 'Персонаж не соответствует минимальному количеству достижений (' . MIN_ACHIEVEMENTS . ').',
        'level_fail'            => 'Уровень персонажа превышает допустимый максимум (' . MAX_LEVEL . ').',
        'blacklisted'           => 'Ваша учётная запись в чёрном списке переносов.',
        'invalid_dump'          => 'Дамп персонажа недействителен или повреждён.',
        'dump_apply_error'      => 'Ошибка применения дампа. Свяжитесь с администратором.',
        'reason_label'          => 'Причина',
        'instructions_title'    => 'Как перенести персонажа',
        'instructions'          => '<ol>
            <li>На <strong>исходном</strong> сервере установите аддон <code>chardump</code>.</li>
            <li>Войдите в игру и введите <code>/chardump</code> — будет создан файл.</li>
            <li>Найдите <code>chardump.lua</code> в папке WTF вашего клиента.</li>
            <li>Загрузите этот файл здесь через кнопку ниже.</li>
            <li>GM рассмотрит ваш запрос в течение 24-48 часов.</li>
            <li>Вы получите уведомление, когда персонаж будет готов.</li>
        </ol>',
        'realm_select'          => 'Целевой реалм',
        'select_realm'          => '— Выберите реалм —',
        'upload_label'          => 'Файл chardump.lua',
        'char_name_label'       => 'Имя персонажа на этом сервере',
        'char_name_hint'        => 'Только буквы, 2-16 символов. Без пробелов и цифр.',
        'confirm_cancel'        => 'Подтвердить отмену этого переноса?',
        'confirm_approve'       => 'Одобрить этот перенос?',
        'confirm_deny'          => 'Отклонить этот перенос?',
        'deny_reason'           => 'Причина отклонения',
        'items_sent'            => 'Предметы повторно отправлены игровой почтой.',
        'token_error'           => 'Ошибка безопасности. Перезагрузите страницу и попробуйте снова.',
        'char_online_error'     => 'Персонаж должен быть офлайн.',
        'transfer_not_pending'  => 'Этот перенос не находится в состоянии ожидания.',
    ],

    // ── PORTUGUÊS ───────────────────────────────────────────────
    'pt' => [
        'site_title'            => 'Migrador — AzerothCore',
        'app_name'              => 'Migrador AC',
        'login_title'           => 'Entrar',
        'login_user'            => 'Usuário',
        'login_pass'            => 'Senha',
        'login_btn'             => 'Entrar',
        'login_footer'          => 'Use as mesmas credenciais do jogo.',
        'login_error'           => 'Usuário ou senha incorretos.',
        'login_locked'          => 'Esta conta está bloqueada.',
        'login_rate_limited'    => 'Muitas tentativas falhas. Tente novamente em alguns minutos.',
        'logout'                => 'Sair',
        'welcome'               => 'Bem-vindo',
        'transfer_title'        => 'Transferência de Personagem',
        'transfer_step1'        => 'Passo 1 — Enviar dump do personagem',
        'transfer_step2'        => 'Passo 2 — Confirmar nome do personagem',
        'transfer_status_0'     => 'Em andamento',
        'transfer_status_1'     => 'Aprovado',
        'transfer_status_2'     => 'Negado',
        'transfer_status_3'     => 'Cancelado',
        'transfer_status_4'     => 'Reenviado',
        'btn_approve'           => 'Aprovar',
        'btn_deny'              => 'Negar',
        'btn_resend'            => 'Reenviar',
        'btn_cancel'            => 'Cancelar',
        'btn_submit'            => 'Enviar',
        'btn_upload'            => 'Enviar arquivo',
        'btn_confirm'           => 'Confirmar',
        'btn_back'              => '← Voltar',
        'gm_panel'              => 'Painel de Administração',
        'player_panel'          => 'Minhas Transferências',
        'no_transfers'          => 'Nenhuma transferência encontrada.',
        'access_denied'         => 'Acesso negado.',
        'server_offline'        => 'O servidor está offline no momento.',
        'invalid_file'          => 'Arquivo inválido. Apenas chardump.lua gerado pelo addon é aceito.',
        'invalid_char_name'     => 'Nome inválido (apenas letras, 2-16 caracteres).',
        'name_taken'            => 'Esse nome de personagem já está em uso neste servidor.',
        'transfer_queued'       => '✔ Sua transferência foi registrada e está em análise. Um GM irá processá-la em breve.',
        'transfer_cancelled'    => 'Transferência cancelada com sucesso.',
        'transfer_approved'     => '✔ Transferência aprovada. O personagem foi atribuído à sua conta.',
        'transfer_denied'       => 'Transferência negada.',
        'achievement_fail'      => 'Seu personagem não atende ao mínimo de conquistas exigido (' . MIN_ACHIEVEMENTS . ').',
        'level_fail'            => 'O nível do personagem excede o máximo permitido (' . MAX_LEVEL . ').',
        'blacklisted'           => 'Sua conta está na lista negra de transferências.',
        'invalid_dump'          => 'O dump do personagem é inválido ou está corrompido.',
        'dump_apply_error'      => 'Erro ao aplicar o dump no banco de dados. Contate um administrador.',
        'reason_label'          => 'Motivo',
        'instructions_title'    => 'Como transferir seu personagem',
        'instructions'          => '<ol>
            <li>No servidor de <strong>origem</strong>, instale o addon <code>chardump</code>.</li>
            <li>Entre no jogo e digite <code>/chardump</code> — o arquivo será gerado.</li>
            <li>Localize o arquivo <code>chardump.lua</code> na pasta WTF do seu cliente.</li>
            <li>Envie esse arquivo aqui usando o botão abaixo.</li>
            <li>Um GM analisará sua solicitação em até 24-48 horas.</li>
            <li>Você receberá uma notificação quando o personagem estiver pronto.</li>
        </ol>',
        'realm_select'          => 'Realm de destino',
        'select_realm'          => '— Selecione um realm —',
        'upload_label'          => 'Arquivo chardump.lua',
        'char_name_label'       => 'Nome do personagem neste servidor',
        'char_name_hint'        => 'Apenas letras, 2-16 caracteres. Sem espaços ou números.',
        'confirm_cancel'        => 'Confirma o cancelamento desta transferência?',
        'confirm_approve'       => 'Aprovar esta transferência?',
        'confirm_deny'          => 'Negar esta transferência?',
        'deny_reason'           => 'Motivo da negação',
        'items_sent'            => 'Os itens foram reenviados por correio no jogo.',
        'token_error'           => 'Erro de segurança. Recarregue a página e tente novamente.',
        'char_online_error'     => 'O personagem deve estar offline.',
        'transfer_not_pending'  => 'Esta transferência não está pendente.',
    ],
];

/**
 * Idiomas que el jugador puede elegir desde el selector de la UI.
 * Clave => nombre a mostrar (en su propio idioma).
 */
const AVAILABLE_LANGS = [
    'es' => 'Español',
    'en' => 'English',
    'fr' => 'Français',
    'de' => 'Deutsch',
    'ru' => 'Русский',
    'pt' => 'Português',
];
$LANG = array_replace_recursive($LANG, [
    'es' => [
        'gm_level' => 'GM Nv.',
        'btn_start_transfer' => 'Iniciar transferencia',
        'btn_refresh' => 'Actualizar',
        'btn_cancel_plain' => 'Cancelar',
        'table_character' => 'Personaje',
        'table_realm' => 'Realm',
        'table_account' => 'Cuenta',
        'table_status' => 'Estado',
        'table_date' => 'Fecha',
        'table_reason' => 'Motivo',
        'table_actions' => 'Acciones',
        'confirm_resend' => '¿Reenviar items?',
        'deny_reason_placeholder' => 'Escribe el motivo aquí…',
        'js_deny_reason_required' => 'Escribe un motivo de denegación',
        'js_lua_only' => 'Solo se aceptan archivos .lua',
        'invalid_realm' => 'Realm inválido.',
        'file_too_large' => 'El archivo supera el tamaño máximo (5 MB).',
        'file_drop_prompt' => 'Haz clic o arrastra aquí tu <code>chardump.lua</code>',
        'redirecting' => 'Redirigiendo...',
        'redirect_link' => 'Clic aquí si no redirige',
        'step2_preview_title' => 'Vista previa del personaje',
        'btn_change_dump' => 'Cambiar dump',
        'fallback_character' => 'Personaje',
        'label_level' => 'Nivel',
        'loading_model' => 'Cargando modelo…',
        'view_wowhead' => 'Ver en WoWHead',
        'stat_gold' => 'Oro',
        'stat_honor' => 'Honor',
        'stat_arena' => 'Arena',
        'stat_backpack' => 'Mochila',
        'stat_bank' => 'Banco',
        'stat_spells' => 'Spells',
        'stat_talents' => 'Talentos',
        'stat_glyphs' => 'Glifos',
        'unit_items' => 'items',
        'inv_more' => '… y %d más',
        'confirm_transfer' => 'Confirmar transferencia',
        'confirm_transfer_help' => 'Revisa que todo esté correcto en el panel de arriba. Puedes cambiar el nombre si ya está en uso en este servidor. Al confirmar, la transferencia quedará <strong>pendiente de aprobación GM</strong>.',
        'char_name_server' => 'Nombre del personaje en el servidor',
        'char_name_placeholder' => 'Ej: Traspaso',
        'char_name_hint_short' => 'Solo letras, 2-12 caracteres.',
        'btn_confirm_submit_gm' => 'Confirmar y enviar solicitud al GM',
        'unrecognized_dump' => 'El dump no tiene un formato reconocible.',
        'back_step1' => 'Vuelve al paso 1',
        'quality_poor' => 'Malo',
        'quality_common' => 'Común',
        'quality_uncommon' => 'Poco común',
        'quality_rare' => 'Raro',
        'quality_epic' => 'Épico',
        'quality_legendary' => 'Legendario',
        'quality_artifact' => 'Artefacto',
        'quality_heirloom' => 'Reliquia',
        'unknown_quality' => 'Calidad desconocida',
        'unknown_m' => 'Desconocido',
        'unknown_f' => 'Desconocida',
        'gender_male' => 'Masculino',
        'gender_female' => 'Femenino',
        'item_redirected_bag' => 'Item redirigido a mochila',
        'item_level' => 'Nivel de item %d',
        'requires_level' => 'Requiere nivel %d',
        'quantity' => 'Cantidad %d',
        'damage_type' => 'daño %s',
        'speed' => 'Velocidad',
        'armor' => 'armadura',
        'block' => 'bloqueo',
        'resistance_to' => 'resistencia a %s',
        'durability' => 'Durabilidad',
        'item_set' => 'Set de objeto',
        'enchantment' => 'Encantamiento',
        'socket_bonus' => 'Bonus de socket',
        'socket_empty' => 'Hueco %s',
        'gem' => 'Gema #%d',
        'spell' => 'Hechizo %d',
        'stackable' => 'apilable %d',
        'maximum' => 'máximo %d',
        'duration_index' => 'duración %d',
        'cooldown_abbr' => 'CD',
        'bag' => 'Bolsa',
        'slot' => 'Slot %d',
        'color' => 'Color %d',
        'type' => 'Tipo %d',
        'race_1' => 'Humano', 'race_2' => 'Orco', 'race_3' => 'Enano', 'race_4' => 'Elfo de noche', 'race_5' => 'No-muerto', 'race_6' => 'Tauren', 'race_7' => 'Gnomo', 'race_8' => 'Trol', 'race_10' => 'Elfo de sangre', 'race_11' => 'Draenei',
        'class_1' => 'Guerrero', 'class_2' => 'Paladín', 'class_3' => 'Cazador', 'class_4' => 'Pícaro', 'class_5' => 'Sacerdote', 'class_6' => 'Caballero M', 'class_7' => 'Chamán', 'class_8' => 'Mago', 'class_9' => 'Brujo', 'class_11' => 'Druida',
    ],
    'en' => [
        'gm_level' => 'GM Lvl',
        'btn_start_transfer' => 'Start transfer',
        'btn_refresh' => 'Refresh',
        'btn_cancel_plain' => 'Cancel',
        'table_character' => 'Character',
        'table_realm' => 'Realm',
        'table_account' => 'Account',
        'table_status' => 'Status',
        'table_date' => 'Date',
        'table_reason' => 'Reason',
        'table_actions' => 'Actions',
        'confirm_resend' => 'Resend items?',
        'deny_reason_placeholder' => 'Write the reason here…',
        'js_deny_reason_required' => 'Write a denial reason',
        'js_lua_only' => 'Only .lua files are accepted',
        'invalid_realm' => 'Invalid realm.',
        'file_too_large' => 'The file exceeds the maximum size (5 MB).',
        'file_drop_prompt' => 'Click or drag your <code>chardump.lua</code> here',
        'redirecting' => 'Redirecting...',
        'redirect_link' => 'Click here if you are not redirected',
        'step2_preview_title' => 'Character preview',
        'btn_change_dump' => 'Change dump',
        'fallback_character' => 'Character',
        'label_level' => 'Level',
        'loading_model' => 'Loading model…',
        'view_wowhead' => 'View on WoWHead',
        'stat_gold' => 'Gold',
        'stat_honor' => 'Honor',
        'stat_arena' => 'Arena',
        'stat_backpack' => 'Backpack',
        'stat_bank' => 'Bank',
        'stat_spells' => 'Spells',
        'stat_talents' => 'Talents',
        'stat_glyphs' => 'Glyphs',
        'unit_items' => 'items',
        'inv_more' => '… and %d more',
        'confirm_transfer' => 'Confirm transfer',
        'confirm_transfer_help' => 'Review that everything is correct in the panel above. You can change the name if it is already used on this server. After confirming, the transfer will remain <strong>pending GM approval</strong>.',
        'char_name_server' => 'Character name on the server',
        'char_name_placeholder' => 'Ex: Transfer',
        'char_name_hint_short' => 'Letters only, 2-12 characters.',
        'btn_confirm_submit_gm' => 'Confirm and send request to GM',
        'unrecognized_dump' => 'The dump is not in a recognized format.',
        'back_step1' => 'Go back to step 1',
        'quality_poor' => 'Poor',
        'quality_common' => 'Common',
        'quality_uncommon' => 'Uncommon',
        'quality_rare' => 'Rare',
        'quality_epic' => 'Epic',
        'quality_legendary' => 'Legendary',
        'quality_artifact' => 'Artifact',
        'quality_heirloom' => 'Heirloom',
        'unknown_quality' => 'Unknown quality',
        'unknown_m' => 'Unknown',
        'unknown_f' => 'Unknown',
        'gender_male' => 'Male',
        'gender_female' => 'Female',
        'item_redirected_bag' => 'Item redirected to backpack',
        'item_level' => 'Item level %d',
        'requires_level' => 'Requires level %d',
        'quantity' => 'Quantity %d',
        'damage_type' => '%s damage',
        'speed' => 'Speed',
        'armor' => 'armor',
        'block' => 'block',
        'resistance_to' => 'resistance to %s',
        'durability' => 'Durability',
        'item_set' => 'Item set',
        'enchantment' => 'Enchantment',
        'socket_bonus' => 'Socket bonus',
        'socket_empty' => 'Empty %s socket',
        'gem' => 'Gem #%d',
        'spell' => 'Spell %d',
        'stackable' => 'stackable %d',
        'maximum' => 'maximum %d',
        'duration_index' => 'duration %d',
        'cooldown_abbr' => 'CD',
        'bag' => 'Bag',
        'slot' => 'Slot %d',
        'color' => 'Color %d',
        'type' => 'Type %d',
        'race_1' => 'Human', 'race_2' => 'Orc', 'race_3' => 'Dwarf', 'race_4' => 'Night Elf', 'race_5' => 'Undead', 'race_6' => 'Tauren', 'race_7' => 'Gnome', 'race_8' => 'Troll', 'race_10' => 'Blood Elf', 'race_11' => 'Draenei',
        'class_1' => 'Warrior', 'class_2' => 'Paladin', 'class_3' => 'Hunter', 'class_4' => 'Rogue', 'class_5' => 'Priest', 'class_6' => 'Death Knight', 'class_7' => 'Shaman', 'class_8' => 'Mage', 'class_9' => 'Warlock', 'class_11' => 'Druid',
    ],
    'fr' => [
        'gm_level' => 'Niv. GM', 'btn_start_transfer' => 'Démarrer le transfert', 'btn_refresh' => 'Actualiser', 'btn_cancel_plain' => 'Annuler',
        'table_character' => 'Personnage', 'table_realm' => 'Realm', 'table_account' => 'Compte', 'table_status' => 'Statut', 'table_date' => 'Date', 'table_reason' => 'Motif', 'table_actions' => 'Actions',
        'confirm_resend' => 'Renvoyer les objets ?', 'deny_reason_placeholder' => 'Écrivez le motif ici…', 'js_deny_reason_required' => 'Écrivez un motif de refus', 'js_lua_only' => 'Seuls les fichiers .lua sont acceptés',
        'invalid_realm' => 'Realm invalide.', 'file_too_large' => 'Le fichier dépasse la taille maximale (5 Mo).', 'file_drop_prompt' => 'Cliquez ou glissez votre <code>chardump.lua</code> ici',
        'redirecting' => 'Redirection...', 'redirect_link' => 'Cliquez ici si vous n’êtes pas redirigé', 'step2_preview_title' => 'Aperçu du personnage', 'btn_change_dump' => 'Changer le dump',
        'fallback_character' => 'Personnage', 'label_level' => 'Niveau', 'loading_model' => 'Chargement du modèle…', 'view_wowhead' => 'Voir sur WoWHead',
        'stat_gold' => 'Or', 'stat_honor' => 'Honneur', 'stat_arena' => 'Arène', 'stat_backpack' => 'Sac', 'stat_bank' => 'Banque', 'stat_spells' => 'Sorts', 'stat_talents' => 'Talents', 'stat_glyphs' => 'Glyphes', 'unit_items' => 'objets', 'inv_more' => '… et %d de plus',
        'confirm_transfer' => 'Confirmer le transfert', 'confirm_transfer_help' => 'Vérifiez que tout est correct dans le panneau ci-dessus. Vous pouvez changer le nom s’il est déjà utilisé sur ce serveur. Après confirmation, le transfert restera <strong>en attente d’approbation GM</strong>.',
        'char_name_server' => 'Nom du personnage sur le serveur', 'char_name_placeholder' => 'Ex : Transfert', 'char_name_hint_short' => 'Lettres uniquement, 2-12 caractères.', 'btn_confirm_submit_gm' => 'Confirmer et envoyer la demande au GM',
        'unrecognized_dump' => 'Le dump n’a pas un format reconnu.', 'back_step1' => 'Retour à l’étape 1',
    ],
    'de' => [
        'gm_level' => 'GM-Stufe', 'btn_start_transfer' => 'Transfer starten', 'btn_refresh' => 'Aktualisieren', 'btn_cancel_plain' => 'Abbrechen',
        'table_character' => 'Charakter', 'table_realm' => 'Realm', 'table_account' => 'Konto', 'table_status' => 'Status', 'table_date' => 'Datum', 'table_reason' => 'Grund', 'table_actions' => 'Aktionen',
        'confirm_resend' => 'Items erneut senden?', 'deny_reason_placeholder' => 'Grund hier eingeben…', 'js_deny_reason_required' => 'Gib einen Ablehnungsgrund ein', 'js_lua_only' => 'Nur .lua-Dateien werden akzeptiert',
        'invalid_realm' => 'Ungültiger Realm.', 'file_too_large' => 'Die Datei überschreitet die maximale Größe (5 MB).', 'file_drop_prompt' => 'Klicke oder ziehe deine <code>chardump.lua</code> hierher',
        'redirecting' => 'Weiterleitung...', 'redirect_link' => 'Hier klicken, falls keine Weiterleitung erfolgt', 'step2_preview_title' => 'Charaktervorschau', 'btn_change_dump' => 'Dump ändern',
        'fallback_character' => 'Charakter', 'label_level' => 'Stufe', 'loading_model' => 'Modell wird geladen…', 'view_wowhead' => 'Auf WoWHead ansehen',
        'stat_gold' => 'Gold', 'stat_honor' => 'Ehre', 'stat_arena' => 'Arena', 'stat_backpack' => 'Rucksack', 'stat_bank' => 'Bank', 'stat_spells' => 'Zauber', 'stat_talents' => 'Talente', 'stat_glyphs' => 'Glyphen', 'unit_items' => 'Items', 'inv_more' => '… und %d mehr',
        'confirm_transfer' => 'Transfer bestätigen', 'confirm_transfer_help' => 'Prüfe, ob im oberen Bereich alles korrekt ist. Du kannst den Namen ändern, falls er auf diesem Server bereits verwendet wird. Nach der Bestätigung bleibt der Transfer <strong>zur GM-Genehmigung ausstehend</strong>.',
        'char_name_server' => 'Charaktername auf dem Server', 'char_name_placeholder' => 'Bsp.: Transfer', 'char_name_hint_short' => 'Nur Buchstaben, 2-12 Zeichen.', 'btn_confirm_submit_gm' => 'Bestätigen und Anfrage an GM senden',
        'unrecognized_dump' => 'Der Dump hat kein erkanntes Format.', 'back_step1' => 'Zurück zu Schritt 1',
    ],
    'ru' => [
        'gm_level' => 'Ур. GM', 'btn_start_transfer' => 'Начать перенос', 'btn_refresh' => 'Обновить', 'btn_cancel_plain' => 'Отмена',
        'table_character' => 'Персонаж', 'table_realm' => 'Realm', 'table_account' => 'Аккаунт', 'table_status' => 'Статус', 'table_date' => 'Дата', 'table_reason' => 'Причина', 'table_actions' => 'Действия',
        'confirm_resend' => 'Отправить предметы повторно?', 'deny_reason_placeholder' => 'Введите причину здесь…', 'js_deny_reason_required' => 'Введите причину отказа', 'js_lua_only' => 'Разрешены только файлы .lua',
        'invalid_realm' => 'Недопустимый realm.', 'file_too_large' => 'Файл превышает максимальный размер (5 МБ).', 'file_drop_prompt' => 'Нажмите или перетащите сюда ваш <code>chardump.lua</code>',
        'redirecting' => 'Перенаправление...', 'redirect_link' => 'Нажмите здесь, если перенаправление не произошло', 'step2_preview_title' => 'Предпросмотр персонажа', 'btn_change_dump' => 'Сменить dump',
        'fallback_character' => 'Персонаж', 'label_level' => 'Уровень', 'loading_model' => 'Загрузка модели…', 'view_wowhead' => 'Открыть в WoWHead',
        'stat_gold' => 'Золото', 'stat_honor' => 'Честь', 'stat_arena' => 'Арена', 'stat_backpack' => 'Сумка', 'stat_bank' => 'Банк', 'stat_spells' => 'Заклинания', 'stat_talents' => 'Таланты', 'stat_glyphs' => 'Символы', 'unit_items' => 'предм.', 'inv_more' => '… и еще %d',
        'confirm_transfer' => 'Подтвердить перенос', 'confirm_transfer_help' => 'Проверьте, что все данные в панели выше верны. Вы можете изменить имя, если оно уже используется на этом сервере. После подтверждения перенос останется <strong>на одобрении GM</strong>.',
        'char_name_server' => 'Имя персонажа на сервере', 'char_name_placeholder' => 'Напр.: Transfer', 'char_name_hint_short' => 'Только буквы, 2-12 символов.', 'btn_confirm_submit_gm' => 'Подтвердить и отправить запрос GM',
        'unrecognized_dump' => 'Dump имеет неизвестный формат.', 'back_step1' => 'Вернуться к шагу 1',
    ],
    'pt' => [
        'gm_level' => 'Nv. GM', 'btn_start_transfer' => 'Iniciar transferência', 'btn_refresh' => 'Atualizar', 'btn_cancel_plain' => 'Cancelar',
        'table_character' => 'Personagem', 'table_realm' => 'Realm', 'table_account' => 'Conta', 'table_status' => 'Estado', 'table_date' => 'Data', 'table_reason' => 'Motivo', 'table_actions' => 'Ações',
        'confirm_resend' => 'Reenviar itens?', 'deny_reason_placeholder' => 'Escreva o motivo aqui…', 'js_deny_reason_required' => 'Escreva um motivo de negação', 'js_lua_only' => 'Apenas arquivos .lua são aceitos',
        'invalid_realm' => 'Realm inválido.', 'file_too_large' => 'O arquivo excede o tamanho máximo (5 MB).', 'file_drop_prompt' => 'Clique ou arraste seu <code>chardump.lua</code> aqui',
        'redirecting' => 'Redirecionando...', 'redirect_link' => 'Clique aqui se não redirecionar', 'step2_preview_title' => 'Prévia do personagem', 'btn_change_dump' => 'Trocar dump',
        'fallback_character' => 'Personagem', 'label_level' => 'Nível', 'loading_model' => 'Carregando modelo…', 'view_wowhead' => 'Ver no WoWHead',
        'stat_gold' => 'Ouro', 'stat_honor' => 'Honra', 'stat_arena' => 'Arena', 'stat_backpack' => 'Mochila', 'stat_bank' => 'Banco', 'stat_spells' => 'Spells', 'stat_talents' => 'Talentos', 'stat_glyphs' => 'Glifos', 'unit_items' => 'itens', 'inv_more' => '… e mais %d',
        'confirm_transfer' => 'Confirmar transferência', 'confirm_transfer_help' => 'Revise se tudo está correto no painel acima. Você pode alterar o nome se ele já estiver em uso neste servidor. Ao confirmar, a transferência ficará <strong>pendente de aprovação GM</strong>.',
        'char_name_server' => 'Nome do personagem no servidor', 'char_name_placeholder' => 'Ex: Transferido', 'char_name_hint_short' => 'Apenas letras, 2-12 caracteres.', 'btn_confirm_submit_gm' => 'Confirmar e enviar solicitação ao GM',
        'unrecognized_dump' => 'O dump não tem um formato reconhecido.', 'back_step1' => 'Voltar ao passo 1',
    ],
]);

// FR_DE_RU_COMPLETE_QUALITY: claves del preview/tooltip completadas para francés, alemán y ruso.
$LANG = array_replace_recursive($LANG, [
    'fr' => [
        'quality_poor' => 'Médiocre',
        'quality_common' => 'Commun',
        'quality_uncommon' => 'Peu commun',
        'quality_rare' => 'Rare',
        'quality_epic' => 'Épique',
        'quality_legendary' => 'Légendaire',
        'quality_artifact' => 'Artéfact',
        'quality_heirloom' => 'Legs',
        'unknown_quality' => 'Qualité inconnue',
        'unknown_m' => 'Inconnu',
        'unknown_f' => 'Inconnue',
        'gender_male' => 'Masculin',
        'gender_female' => 'Féminin',
        'item_redirected_bag' => 'Objet redirigé vers le sac à dos',
        'item_level' => 'Niveau d\'objet %d',
        'requires_level' => 'Niveau requis : %d',
        'quantity' => 'Quantité %d',
        'damage_type' => 'dégâts %s',
        'speed' => 'Vitesse',
        'armor' => 'armure',
        'block' => 'blocage',
        'resistance_to' => 'résistance à %s',
        'durability' => 'Durabilité',
        'item_set' => 'Ensemble d\'objets',
        'enchantment' => 'Enchantement',
        'socket_bonus' => 'Bonus d\'emplacement',
        'socket_empty' => 'Emplacement %s vide',
        'gem' => 'Gemme n°%d',
        'spell' => 'Sort %d',
        'stackable' => 'empilable %d',
        'maximum' => 'maximum %d',
        'duration_index' => 'durée %d',
        'cooldown_abbr' => 'Récup.',
        'bag' => 'Sac',
        'slot' => 'Emplacement %d',
        'color' => 'Couleur %d',
        'type' => 'Type %d',
        'race_1' => 'Humain', 'race_2' => 'Orc', 'race_3' => 'Nain', 'race_4' => 'Elfe de la nuit', 'race_5' => 'Mort-vivant', 'race_6' => 'Tauren', 'race_7' => 'Gnome', 'race_8' => 'Troll', 'race_10' => 'Elfe de sang', 'race_11' => 'Draenei',
        'class_1' => 'Guerrier', 'class_2' => 'Paladin', 'class_3' => 'Chasseur', 'class_4' => 'Voleur', 'class_5' => 'Prêtre', 'class_6' => 'Chevalier de la mort', 'class_7' => 'Chaman', 'class_8' => 'Mage', 'class_9' => 'Démoniste', 'class_11' => 'Druide',
    ],
    'de' => [
        'quality_poor' => 'Schlecht',
        'quality_common' => 'Gewöhnlich',
        'quality_uncommon' => 'Ungewöhnlich',
        'quality_rare' => 'Selten',
        'quality_epic' => 'Episch',
        'quality_legendary' => 'Legendär',
        'quality_artifact' => 'Artefakt',
        'quality_heirloom' => 'Erbstück',
        'unknown_quality' => 'Unbekannte Qualität',
        'unknown_m' => 'Unbekannt',
        'unknown_f' => 'Unbekannt',
        'gender_male' => 'Männlich',
        'gender_female' => 'Weiblich',
        'item_redirected_bag' => 'Gegenstand in den Rucksack umgeleitet',
        'item_level' => 'Gegenstandsstufe %d',
        'requires_level' => 'Erfordert Stufe %d',
        'quantity' => 'Anzahl %d',
        'damage_type' => '%s-Schaden',
        'speed' => 'Geschwindigkeit',
        'armor' => 'Rüstung',
        'block' => 'Blockwert',
        'resistance_to' => 'Resistenz gegen %s',
        'durability' => 'Haltbarkeit',
        'item_set' => 'Set',
        'enchantment' => 'Verzauberung',
        'socket_bonus' => 'Sockelbonus',
        'socket_empty' => 'Leerer %s-Sockel',
        'gem' => 'Edelstein Nr. %d',
        'spell' => 'Zauber %d',
        'stackable' => 'stapelbar %d',
        'maximum' => 'maximal %d',
        'duration_index' => 'Dauer %d',
        'cooldown_abbr' => 'Abklingzeit',
        'bag' => 'Tasche',
        'slot' => 'Slot %d',
        'color' => 'Farbe %d',
        'type' => 'Typ %d',
        'race_1' => 'Mensch', 'race_2' => 'Orc', 'race_3' => 'Zwerg', 'race_4' => 'Nachtelf', 'race_5' => 'Untoter', 'race_6' => 'Tauren', 'race_7' => 'Gnom', 'race_8' => 'Troll', 'race_10' => 'Blutelf', 'race_11' => 'Draenei',
        'class_1' => 'Krieger', 'class_2' => 'Paladin', 'class_3' => 'Jäger', 'class_4' => 'Schurke', 'class_5' => 'Priester', 'class_6' => 'Todesritter', 'class_7' => 'Schamane', 'class_8' => 'Magier', 'class_9' => 'Hexenmeister', 'class_11' => 'Druide',
    ],
    'ru' => [
        'quality_poor' => 'Плохое',
        'quality_common' => 'Обычное',
        'quality_uncommon' => 'Необычное',
        'quality_rare' => 'Редкое',
        'quality_epic' => 'Эпическое',
        'quality_legendary' => 'Легендарное',
        'quality_artifact' => 'Артефакт',
        'quality_heirloom' => 'Реликвия',
        'unknown_quality' => 'Неизвестное качество',
        'unknown_m' => 'Неизвестно',
        'unknown_f' => 'Неизвестно',
        'gender_male' => 'Мужской',
        'gender_female' => 'Женский',
        'item_redirected_bag' => 'Предмет перенаправлен в рюкзак',
        'item_level' => 'Уровень предмета %d',
        'requires_level' => 'Требуется уровень %d',
        'quantity' => 'Количество %d',
        'damage_type' => 'урон: %s',
        'speed' => 'Скорость',
        'armor' => 'броня',
        'block' => 'блок',
        'resistance_to' => 'сопротивление %s',
        'durability' => 'Прочность',
        'item_set' => 'Комплект предметов',
        'enchantment' => 'Чары',
        'socket_bonus' => 'Бонус гнёзд',
        'socket_empty' => 'Пустое гнездо (%s)',
        'gem' => 'Самоцвет #%d',
        'spell' => 'Заклинание %d',
        'stackable' => 'в стопке %d',
        'maximum' => 'максимум %d',
        'duration_index' => 'длительность %d',
        'cooldown_abbr' => 'Откат',
        'bag' => 'Сумка',
        'slot' => 'Слот %d',
        'color' => 'Цвет %d',
        'type' => 'Тип %d',
        'race_1' => 'Человек', 'race_2' => 'Орк', 'race_3' => 'Дворф', 'race_4' => 'Ночной эльф', 'race_5' => 'Нежить', 'race_6' => 'Таурен', 'race_7' => 'Гном', 'race_8' => 'Тролль', 'race_10' => 'Эльф крови', 'race_11' => 'Дреней',
        'class_1' => 'Воин', 'class_2' => 'Паладин', 'class_3' => 'Охотник', 'class_4' => 'Разбойник', 'class_5' => 'Жрец', 'class_6' => 'Рыцарь смерти', 'class_7' => 'Шаман', 'class_8' => 'Маг', 'class_9' => 'Чернокнижник', 'class_11' => 'Друид',
    ],
]);

// PT_COMPLETE_QUALITY: claves del preview/tooltip completadas para portugués.
$LANG = array_replace_recursive($LANG, [
    'pt' => [
        'quality_poor' => 'Ruim',
        'quality_common' => 'Comum',
        'quality_uncommon' => 'Incomum',
        'quality_rare' => 'Raro',
        'quality_epic' => 'Épico',
        'quality_legendary' => 'Lendário',
        'quality_artifact' => 'Artefato',
        'quality_heirloom' => 'Herança',
        'unknown_quality' => 'Qualidade desconhecida',
        'unknown_m' => 'Desconhecido',
        'unknown_f' => 'Desconhecida',
        'gender_male' => 'Masculino',
        'gender_female' => 'Feminino',
        'item_redirected_bag' => 'Item redirecionado para a mochila',
        'item_level' => 'Nível do item %d',
        'requires_level' => 'Requer nível %d',
        'quantity' => 'Quantidade %d',
        'damage_type' => 'dano %s',
        'speed' => 'Velocidade',
        'armor' => 'armadura',
        'block' => 'bloqueio',
        'resistance_to' => 'resistência a %s',
        'durability' => 'Durabilidade',
        'item_set' => 'Conjunto de item',
        'enchantment' => 'Encantamento',
        'socket_bonus' => 'Bônus de encaixe',
        'socket_empty' => 'Encaixe %s vazio',
        'gem' => 'Gema #%d',
        'spell' => 'Feitiço %d',
        'stackable' => 'empilhável %d',
        'maximum' => 'máximo %d',
        'duration_index' => 'duração %d',
        'cooldown_abbr' => 'Recarga',
        'bag' => 'Bolsa',
        'slot' => 'Slot %d',
        'color' => 'Cor %d',
        'type' => 'Tipo %d',
        'race_1' => 'Humano',
        'race_2' => 'Orc',
        'race_3' => 'Anão',
        'race_4' => 'Elfo Noturno',
        'race_5' => 'Morto-vivo',
        'race_6' => 'Tauren',
        'race_7' => 'Gnomo',
        'race_8' => 'Troll',
        'race_10' => 'Elfo Sangrento',
        'race_11' => 'Draenei',
        'class_1' => 'Guerreiro',
        'class_2' => 'Paladino',
        'class_3' => 'Caçador',
        'class_4' => 'Ladino',
        'class_5' => 'Sacerdote',
        'class_6' => 'Cavaleiro da Morte',
        'class_7' => 'Xamã',
        'class_8' => 'Mago',
        'class_9' => 'Bruxo',
        'class_11' => 'Druida',
    ],
]);

// TOOLTIP_VOCAB: nombres de stats, clases de objeto, sockets, triggers de
// hechizo, slots de equipo y textos varios usados en el preview/tooltip de
// items (transfer/step2.php) y en los mensajes de las acciones GM (b_*.php).
$LANG = array_replace_recursive($LANG, [
    'es' => [
        'stat_3' => 'Agilidad', 'stat_4' => 'Fuerza', 'stat_5' => 'Intelecto', 'stat_6' => 'Espíritu', 'stat_7' => 'Aguante',
        'stat_12' => 'Índice de defensa', 'stat_13' => 'Índice de esquivar', 'stat_14' => 'Índice de parar',
        'stat_15' => 'Índice de bloqueo', 'stat_16' => 'Índice de golpe cuerpo a cuerpo',
        'stat_17' => 'Índice de golpe a distancia', 'stat_18' => 'Índice de golpe con hechizos',
        'stat_19' => 'Índice de crítico cuerpo a cuerpo', 'stat_20' => 'Índice de crítico a distancia',
        'stat_21' => 'Índice de crítico con hechizos', 'stat_28' => 'Índice de celeridad cuerpo a cuerpo',
        'stat_29' => 'Índice de celeridad a distancia', 'stat_30' => 'Índice de celeridad con hechizos',
        'stat_31' => 'Índice de golpe', 'stat_32' => 'Índice de golpe crítico', 'stat_35' => 'Índice de temple',
        'stat_36' => 'Índice de celeridad', 'stat_37' => 'Índice de pericia', 'stat_38' => 'Poder de ataque',
        'stat_39' => 'Poder de ataque a distancia', 'stat_40' => 'Poder de ataque feral',
        'stat_41' => 'Sanación', 'stat_42' => 'Daño con hechizos', 'stat_43' => 'Maná cada 5 s',
        'stat_44' => 'Penetración de armadura', 'stat_45' => 'Poder con hechizos',
        'stat_46' => 'Salud cada 5 s', 'stat_47' => 'Penetración de hechizos', 'stat_48' => 'Valor de bloqueo',
        'stat_unknown' => 'Stat %d',
        'dmgschool_0' => 'Físico', 'dmgschool_1' => 'Sagrado', 'dmgschool_2' => 'Fuego', 'dmgschool_3' => 'Naturaleza', 'dmgschool_4' => 'Escarcha', 'dmgschool_5' => 'Sombras', 'dmgschool_6' => 'Arcano',
        'iclass_0' => 'Consumible', 'iclass_1' => 'Contenedor', 'iclass_2' => 'Arma', 'iclass_3' => 'Gema', 'iclass_4' => 'Armadura',
        'iclass_5' => 'Componente', 'iclass_6' => 'Proyectil', 'iclass_7' => 'Material', 'iclass_9' => 'Receta',
        'iclass_11' => 'Carcaj', 'iclass_12' => 'Misión', 'iclass_13' => 'Llave', 'iclass_15' => 'Misceláneo', 'iclass_16' => 'Glifo',
        'weapon_0' => 'Hacha 1M', 'weapon_1' => 'Hacha 2M', 'weapon_2' => 'Arco', 'weapon_3' => 'Arma de fuego', 'weapon_4' => 'Maza 1M',
        'weapon_5' => 'Maza 2M', 'weapon_6' => 'Asta', 'weapon_7' => 'Espada 1M', 'weapon_8' => 'Espada 2M', 'weapon_10' => 'Bastón',
        'weapon_13' => 'Arma de puño', 'weapon_15' => 'Daga', 'weapon_16' => 'Arrojadiza', 'weapon_18' => 'Ballesta', 'weapon_19' => 'Varita',
        'weapon_20' => 'Caña de pescar',
        'armorsub_0' => 'Misceláneo', 'armorsub_1' => 'Tela', 'armorsub_2' => 'Cuero', 'armorsub_3' => 'Malla', 'armorsub_4' => 'Placas',
        'armorsub_6' => 'Escudo', 'armorsub_7' => 'Tratado', 'armorsub_8' => 'Ídolo', 'armorsub_9' => 'Tótem', 'armorsub_10' => 'Sigilo',
        'bonding_1' => 'Se liga al recogerlo', 'bonding_2' => 'Se liga al equiparlo', 'bonding_3' => 'Se liga al usarlo',
        'bonding_4' => 'Objeto de misión', 'bonding_5' => 'Objeto de misión',
        'socket_color_1' => 'Meta', 'socket_color_2' => 'Rojo', 'socket_color_4' => 'Amarillo', 'socket_color_8' => 'Azul',
        'socket_color_16' => 'Naranja', 'socket_color_32' => 'Morado', 'socket_color_64' => 'Verde', 'socket_color_128' => 'Prism.',
        'socket_generic' => 'Socket',
        'trigger_0' => 'Usar', 'trigger_1' => 'Al equipar', 'trigger_2' => 'Probabilidad al golpear',
        'trigger_4' => 'Aprender hechizo', 'trigger_5' => 'Usar', 'trigger_6' => 'Aprender profesión', 'trigger_generic' => 'Trigger %d',
        'js_loading_viewer' => 'Cargando viewer…', 'js_viewer_ok_direct' => 'Viewer OK (directo)',
        'js_viewer_via_proxy' => 'Viewer vía proxy…', 'js_viewer_ok_proxy' => 'Viewer OK (proxy)',
        'js_loading_library' => 'Cargando librería…', 'js_rendering' => 'Renderizando…', 'js_error_prefix' => 'Error: ',
        'slot_head' => 'Cabeza', 'slot_neck' => 'Cuello', 'slot_shoulders' => 'Hombros', 'slot_shirt' => 'Camisa', 'slot_chest' => 'Pecho',
        'slot_waist' => 'Cintura', 'slot_legs' => 'Piernas', 'slot_feet' => 'Pies', 'slot_wrists' => 'Muñecas', 'slot_hands' => 'Guantes',
        'slot_finger1' => 'Dedo 1', 'slot_finger2' => 'Dedo 2', 'slot_trinket1' => 'Trinket 1', 'slot_trinket2' => 'Trinket 2',
        'slot_back' => 'Espalda', 'slot_mainhand' => 'Mano Ppal.', 'slot_offhand' => 'Mano Sec.', 'slot_ranged' => 'A distancia',
        'slot_tabard' => 'Tabardo', 'slot_bag1' => 'Bolsa 1', 'slot_bag2' => 'Bolsa 2', 'slot_bag3' => 'Bolsa 3', 'slot_bag4' => 'Bolsa 4',
        'invalid_params' => 'Parámetros inválidos.',
        'transfer_not_found' => 'Transferencia no encontrada.',
        'dump_unavailable' => 'El dump no está disponible para importar. Pide al jugador que lo reenvíe.',
        'check_server_logs' => 'Revisa los logs del servidor.',
        'no_reason_specified' => 'Sin motivo especificado',
        'character_not_found' => 'No se encontró el personaje en la base de datos.',
        'mail_subject_transfer_items' => 'Objetos de la transferencia',
        'mail_subject_excess_items' => 'Transferencia — Items adicionales',
        'mail_body_excess_items' => "Estos items no cabían en tu inventario ni en el banco durante la importación.\nPuedes recogerlos aquí.",
        'label_chardump_raw' => 'Chardump',
        'item_placeholder_name' => 'Item #%d',
        'label_entry' => 'Entry',
    ],
    'en' => [
        'stat_3' => 'Agility', 'stat_4' => 'Strength', 'stat_5' => 'Intellect', 'stat_6' => 'Spirit', 'stat_7' => 'Stamina',
        'stat_12' => 'Defense Rating', 'stat_13' => 'Dodge Rating', 'stat_14' => 'Parry Rating',
        'stat_15' => 'Block Rating', 'stat_16' => 'Melee Hit Rating',
        'stat_17' => 'Ranged Hit Rating', 'stat_18' => 'Spell Hit Rating',
        'stat_19' => 'Melee Critical Strike Rating', 'stat_20' => 'Ranged Critical Strike Rating',
        'stat_21' => 'Spell Critical Strike Rating', 'stat_28' => 'Melee Haste Rating',
        'stat_29' => 'Ranged Haste Rating', 'stat_30' => 'Spell Haste Rating',
        'stat_31' => 'Hit Rating', 'stat_32' => 'Critical Strike Rating', 'stat_35' => 'Resilience Rating',
        'stat_36' => 'Haste Rating', 'stat_37' => 'Expertise Rating', 'stat_38' => 'Attack Power',
        'stat_39' => 'Ranged Attack Power', 'stat_40' => 'Feral Attack Power',
        'stat_41' => 'Healing Power', 'stat_42' => 'Spell Damage', 'stat_43' => 'Mana every 5 sec.',
        'stat_44' => 'Armor Penetration', 'stat_45' => 'Spell Power',
        'stat_46' => 'Health every 5 sec.', 'stat_47' => 'Spell Penetration', 'stat_48' => 'Block Value',
        'stat_unknown' => 'Stat %d',
        'dmgschool_0' => 'Physical', 'dmgschool_1' => 'Holy', 'dmgschool_2' => 'Fire', 'dmgschool_3' => 'Nature', 'dmgschool_4' => 'Frost', 'dmgschool_5' => 'Shadow', 'dmgschool_6' => 'Arcane',
        'iclass_0' => 'Consumable', 'iclass_1' => 'Container', 'iclass_2' => 'Weapon', 'iclass_3' => 'Gem', 'iclass_4' => 'Armor',
        'iclass_5' => 'Trade Goods', 'iclass_6' => 'Projectile', 'iclass_7' => 'Reagent', 'iclass_9' => 'Recipe',
        'iclass_11' => 'Quiver', 'iclass_12' => 'Quest', 'iclass_13' => 'Key', 'iclass_15' => 'Miscellaneous', 'iclass_16' => 'Glyph',
        'weapon_0' => 'One-Handed Axe', 'weapon_1' => 'Two-Handed Axe', 'weapon_2' => 'Bow', 'weapon_3' => 'Gun', 'weapon_4' => 'One-Handed Mace',
        'weapon_5' => 'Two-Handed Mace', 'weapon_6' => 'Polearm', 'weapon_7' => 'One-Handed Sword', 'weapon_8' => 'Two-Handed Sword', 'weapon_10' => 'Staff',
        'weapon_13' => 'Fist Weapon', 'weapon_15' => 'Dagger', 'weapon_16' => 'Thrown', 'weapon_18' => 'Crossbow', 'weapon_19' => 'Wand',
        'weapon_20' => 'Fishing Pole',
        'armorsub_0' => 'Miscellaneous', 'armorsub_1' => 'Cloth', 'armorsub_2' => 'Leather', 'armorsub_3' => 'Mail', 'armorsub_4' => 'Plate',
        'armorsub_6' => 'Shield', 'armorsub_7' => 'Libram', 'armorsub_8' => 'Idol', 'armorsub_9' => 'Totem', 'armorsub_10' => 'Sigil',
        'bonding_1' => 'Binds when picked up', 'bonding_2' => 'Binds when equipped', 'bonding_3' => 'Binds when used',
        'bonding_4' => 'Quest Item', 'bonding_5' => 'Quest Item',
        'socket_color_1' => 'Meta', 'socket_color_2' => 'Red', 'socket_color_4' => 'Yellow', 'socket_color_8' => 'Blue',
        'socket_color_16' => 'Orange', 'socket_color_32' => 'Purple', 'socket_color_64' => 'Green', 'socket_color_128' => 'Prism.',
        'socket_generic' => 'Socket',
        'trigger_0' => 'Use', 'trigger_1' => 'On Equip', 'trigger_2' => 'Chance on Hit',
        'trigger_4' => 'Learn Spell', 'trigger_5' => 'Use', 'trigger_6' => 'Learn Profession', 'trigger_generic' => 'Trigger %d',
        'js_loading_viewer' => 'Loading viewer…', 'js_viewer_ok_direct' => 'Viewer OK (direct)',
        'js_viewer_via_proxy' => 'Viewer via proxy…', 'js_viewer_ok_proxy' => 'Viewer OK (proxy)',
        'js_loading_library' => 'Loading library…', 'js_rendering' => 'Rendering…', 'js_error_prefix' => 'Error: ',
        'slot_head' => 'Head', 'slot_neck' => 'Neck', 'slot_shoulders' => 'Shoulders', 'slot_shirt' => 'Shirt', 'slot_chest' => 'Chest',
        'slot_waist' => 'Waist', 'slot_legs' => 'Legs', 'slot_feet' => 'Feet', 'slot_wrists' => 'Wrists', 'slot_hands' => 'Hands',
        'slot_finger1' => 'Finger 1', 'slot_finger2' => 'Finger 2', 'slot_trinket1' => 'Trinket 1', 'slot_trinket2' => 'Trinket 2',
        'slot_back' => 'Back', 'slot_mainhand' => 'Main Hand', 'slot_offhand' => 'Off Hand', 'slot_ranged' => 'Ranged',
        'slot_tabard' => 'Tabard', 'slot_bag1' => 'Bag 1', 'slot_bag2' => 'Bag 2', 'slot_bag3' => 'Bag 3', 'slot_bag4' => 'Bag 4',
        'invalid_params' => 'Invalid parameters.',
        'transfer_not_found' => 'Transfer not found.',
        'dump_unavailable' => 'The dump is not available for import. Ask the player to resend it.',
        'check_server_logs' => 'Check the server logs.',
        'no_reason_specified' => 'No reason specified',
        'character_not_found' => 'Character not found in the database.',
        'mail_subject_transfer_items' => 'Transfer Items',
        'mail_subject_excess_items' => 'Transfer — Additional items',
        'mail_body_excess_items' => "These items didn't fit in your inventory or bank during the import.\nYou can collect them here.",
        'label_chardump_raw' => 'Chardump',
        'item_placeholder_name' => 'Item #%d',
        'label_entry' => 'Entry',
    ],
    'fr' => [
        'stat_3' => 'Agilité', 'stat_4' => 'Force', 'stat_5' => 'Intelligence', 'stat_6' => 'Esprit', 'stat_7' => 'Endurance',
        'stat_12' => 'Évaluation de défense', 'stat_13' => 'Évaluation d\'esquive', 'stat_14' => 'Évaluation de parade',
        'stat_15' => 'Évaluation de blocage', 'stat_16' => 'Évaluation de toucher (corps à corps)',
        'stat_17' => 'Évaluation de toucher (à distance)', 'stat_18' => 'Évaluation de toucher (sorts)',
        'stat_19' => 'Évaluation de coup critique (corps à corps)', 'stat_20' => 'Évaluation de coup critique (à distance)',
        'stat_21' => 'Évaluation de coup critique (sorts)', 'stat_28' => 'Évaluation de hâte (corps à corps)',
        'stat_29' => 'Évaluation de hâte (à distance)', 'stat_30' => 'Évaluation de hâte (sorts)',
        'stat_31' => 'Évaluation de toucher', 'stat_32' => 'Évaluation de coup critique', 'stat_35' => 'Évaluation de résilience',
        'stat_36' => 'Évaluation de hâte', 'stat_37' => 'Évaluation d\'expertise', 'stat_38' => 'Puissance d\'attaque',
        'stat_39' => 'Puissance d\'attaque à distance', 'stat_40' => 'Puissance d\'attaque féroce',
        'stat_41' => 'Guérison', 'stat_42' => 'Dégâts des sorts', 'stat_43' => 'Mana toutes les 5 sec',
        'stat_44' => 'Pénétration d\'armure', 'stat_45' => 'Puissance des sorts',
        'stat_46' => 'Santé toutes les 5 sec', 'stat_47' => 'Pénétration de sorts', 'stat_48' => 'Valeur de blocage',
        'stat_unknown' => 'Stat %d',
        'dmgschool_0' => 'Physique', 'dmgschool_1' => 'Sacré', 'dmgschool_2' => 'Feu', 'dmgschool_3' => 'Nature', 'dmgschool_4' => 'Givre', 'dmgschool_5' => 'Ombre', 'dmgschool_6' => 'Arcane',
        'iclass_0' => 'Consommable', 'iclass_1' => 'Conteneur', 'iclass_2' => 'Arme', 'iclass_3' => 'Gemme', 'iclass_4' => 'Armure',
        'iclass_5' => 'Composant', 'iclass_6' => 'Projectile', 'iclass_7' => 'Réactif', 'iclass_9' => 'Recette',
        'iclass_11' => 'Carquois', 'iclass_12' => 'Quête', 'iclass_13' => 'Clé', 'iclass_15' => 'Divers', 'iclass_16' => 'Glyphe',
        'weapon_0' => 'Hache à une main', 'weapon_1' => 'Hache à deux mains', 'weapon_2' => 'Arc', 'weapon_3' => 'Arme à feu', 'weapon_4' => 'Masse à une main',
        'weapon_5' => 'Masse à deux mains', 'weapon_6' => 'Arme d\'hast', 'weapon_7' => 'Épée à une main', 'weapon_8' => 'Épée à deux mains', 'weapon_10' => 'Bâton',
        'weapon_13' => 'Arme de pugilat', 'weapon_15' => 'Dague', 'weapon_16' => 'Arme de jet', 'weapon_18' => 'Arbalète', 'weapon_19' => 'Baguette',
        'weapon_20' => 'Canne à pêche',
        'armorsub_0' => 'Divers', 'armorsub_1' => 'Tissu', 'armorsub_2' => 'Cuir', 'armorsub_3' => 'Mailles', 'armorsub_4' => 'Plaques',
        'armorsub_6' => 'Bouclier', 'armorsub_7' => 'Manuscrit', 'armorsub_8' => 'Idole', 'armorsub_9' => 'Totem', 'armorsub_10' => 'Sceau',
        'bonding_1' => 'Lié à l\'obtention', 'bonding_2' => 'Lié à l\'équipement', 'bonding_3' => 'Lié à l\'utilisation',
        'bonding_4' => 'Objet de quête', 'bonding_5' => 'Objet de quête',
        'socket_color_1' => 'Méta', 'socket_color_2' => 'Rouge', 'socket_color_4' => 'Jaune', 'socket_color_8' => 'Bleu',
        'socket_color_16' => 'Orange', 'socket_color_32' => 'Violet', 'socket_color_64' => 'Vert', 'socket_color_128' => 'Prisme',
        'socket_generic' => 'Emplacement',
        'trigger_0' => 'Utiliser', 'trigger_1' => 'À l\'équipement', 'trigger_2' => 'Probabilité au toucher',
        'trigger_4' => 'Apprendre un sort', 'trigger_5' => 'Utiliser', 'trigger_6' => 'Apprendre une profession', 'trigger_generic' => 'Trigger %d',
        'js_loading_viewer' => 'Chargement du viewer…', 'js_viewer_ok_direct' => 'Viewer OK (direct)',
        'js_viewer_via_proxy' => 'Viewer via proxy…', 'js_viewer_ok_proxy' => 'Viewer OK (proxy)',
        'js_loading_library' => 'Chargement de la librairie…', 'js_rendering' => 'Rendu en cours…', 'js_error_prefix' => 'Erreur : ',
        'slot_head' => 'Tête', 'slot_neck' => 'Cou', 'slot_shoulders' => 'Épaules', 'slot_shirt' => 'Chemise', 'slot_chest' => 'Torse',
        'slot_waist' => 'Taille', 'slot_legs' => 'Jambes', 'slot_feet' => 'Pieds', 'slot_wrists' => 'Poignets', 'slot_hands' => 'Mains',
        'slot_finger1' => 'Doigt 1', 'slot_finger2' => 'Doigt 2', 'slot_trinket1' => 'Babiole 1', 'slot_trinket2' => 'Babiole 2',
        'slot_back' => 'Dos', 'slot_mainhand' => 'Main droite', 'slot_offhand' => 'Main gauche', 'slot_ranged' => 'Distance',
        'slot_tabard' => 'Tabard', 'slot_bag1' => 'Sac 1', 'slot_bag2' => 'Sac 2', 'slot_bag3' => 'Sac 3', 'slot_bag4' => 'Sac 4',
        'invalid_params' => 'Paramètres invalides.',
        'transfer_not_found' => 'Transfert introuvable.',
        'dump_unavailable' => 'Le dump n\'est pas disponible pour l\'importation. Demandez au joueur de le renvoyer.',
        'check_server_logs' => 'Vérifiez les logs du serveur.',
        'no_reason_specified' => 'Aucun motif spécifié',
        'character_not_found' => 'Personnage introuvable dans la base de données.',
        'mail_subject_transfer_items' => 'Objets du transfert',
        'mail_subject_excess_items' => 'Transfert — Objets supplémentaires',
        'mail_body_excess_items' => "Ces objets ne tenaient pas dans votre inventaire ni dans votre banque lors de l'importation.\nVous pouvez les récupérer ici.",
        'label_chardump_raw' => 'Chardump',
        'item_placeholder_name' => 'Objet #%d',
        'label_entry' => 'Entry',
    ],
    'de' => [
        'stat_3' => 'Beweglichkeit', 'stat_4' => 'Stärke', 'stat_5' => 'Intellekt', 'stat_6' => 'Willenskraft', 'stat_7' => 'Ausdauer',
        'stat_12' => 'Verteidigungswertung', 'stat_13' => 'Ausweichwertung', 'stat_14' => 'Parierwertung',
        'stat_15' => 'Blockwertung', 'stat_16' => 'Waffenkampf-Trefferwertung',
        'stat_17' => 'Fernkampf-Trefferwertung', 'stat_18' => 'Zauber-Trefferwertung',
        'stat_19' => 'Waffenkampf-Krit.-Wertung', 'stat_20' => 'Fernkampf-Krit.-Wertung',
        'stat_21' => 'Zauber-Krit.-Wertung', 'stat_28' => 'Waffenkampf-Tempo-Wertung',
        'stat_29' => 'Fernkampf-Tempo-Wertung', 'stat_30' => 'Zauber-Tempo-Wertung',
        'stat_31' => 'Trefferwertung', 'stat_32' => 'Krit.-Wertung', 'stat_35' => 'Zähigkeitswertung',
        'stat_36' => 'Tempowertung', 'stat_37' => 'Waffenkundewertung', 'stat_38' => 'Angriffskraft',
        'stat_39' => 'Fernkampf-Angriffskraft', 'stat_40' => 'Wildheit-Angriffskraft',
        'stat_41' => 'Heilung', 'stat_42' => 'Zauberschaden', 'stat_43' => 'Mana alle 5 Sek.',
        'stat_44' => 'Rüstungsdurchdringung', 'stat_45' => 'Zauberkraft',
        'stat_46' => 'Leben alle 5 Sek.', 'stat_47' => 'Zauberdurchdringung', 'stat_48' => 'Blockwert',
        'stat_unknown' => 'Stat %d',
        'dmgschool_0' => 'Physisch', 'dmgschool_1' => 'Heilig', 'dmgschool_2' => 'Feuer', 'dmgschool_3' => 'Natur', 'dmgschool_4' => 'Frost', 'dmgschool_5' => 'Schatten', 'dmgschool_6' => 'Arkan',
        'iclass_0' => 'Verbrauchbar', 'iclass_1' => 'Behälter', 'iclass_2' => 'Waffe', 'iclass_3' => 'Edelstein', 'iclass_4' => 'Rüstung',
        'iclass_5' => 'Handelsware', 'iclass_6' => 'Geschoss', 'iclass_7' => 'Reagenz', 'iclass_9' => 'Rezept',
        'iclass_11' => 'Köcher', 'iclass_12' => 'Quest', 'iclass_13' => 'Schlüssel', 'iclass_15' => 'Verschiedenes', 'iclass_16' => 'Glyphe',
        'weapon_0' => 'Einhandaxt', 'weapon_1' => 'Zweihandaxt', 'weapon_2' => 'Bogen', 'weapon_3' => 'Schusswaffe', 'weapon_4' => 'Einhandstreitkolben',
        'weapon_5' => 'Zweihandstreitkolben', 'weapon_6' => 'Stangenwaffe', 'weapon_7' => 'Einhandschwert', 'weapon_8' => 'Zweihandschwert', 'weapon_10' => 'Stab',
        'weapon_13' => 'Faustwaffe', 'weapon_15' => 'Dolch', 'weapon_16' => 'Wurfwaffe', 'weapon_18' => 'Armbrust', 'weapon_19' => 'Zauberstab',
        'weapon_20' => 'Angelrute',
        'armorsub_0' => 'Verschiedenes', 'armorsub_1' => 'Stoff', 'armorsub_2' => 'Leder', 'armorsub_3' => 'Schuppen', 'armorsub_4' => 'Platte',
        'armorsub_6' => 'Schild', 'armorsub_7' => 'Andachtsbuch', 'armorsub_8' => 'Idol', 'armorsub_9' => 'Totem', 'armorsub_10' => 'Siegel',
        'bonding_1' => 'Seelengebunden', 'bonding_2' => 'Bindet sich bei Anlegen', 'bonding_3' => 'Bindet bei Benutzen',
        'bonding_4' => 'Questgegenstand', 'bonding_5' => 'Questgegenstand',
        'socket_color_1' => 'Meta', 'socket_color_2' => 'Rot', 'socket_color_4' => 'Gelb', 'socket_color_8' => 'Blau',
        'socket_color_16' => 'Orange', 'socket_color_32' => 'Lila', 'socket_color_64' => 'Grün', 'socket_color_128' => 'Prism.',
        'socket_generic' => 'Sockel',
        'trigger_0' => 'Benutzen', 'trigger_1' => 'Bei Anlegen', 'trigger_2' => 'Wahrscheinlichkeit bei Treffer',
        'trigger_4' => 'Zauber erlernen', 'trigger_5' => 'Benutzen', 'trigger_6' => 'Beruf erlernen', 'trigger_generic' => 'Trigger %d',
        'js_loading_viewer' => 'Viewer wird geladen…', 'js_viewer_ok_direct' => 'Viewer OK (direkt)',
        'js_viewer_via_proxy' => 'Viewer über Proxy…', 'js_viewer_ok_proxy' => 'Viewer OK (Proxy)',
        'js_loading_library' => 'Bibliothek wird geladen…', 'js_rendering' => 'Rendering…', 'js_error_prefix' => 'Fehler: ',
        'slot_head' => 'Kopf', 'slot_neck' => 'Hals', 'slot_shoulders' => 'Schultern', 'slot_shirt' => 'Hemd', 'slot_chest' => 'Brust',
        'slot_waist' => 'Taille', 'slot_legs' => 'Beine', 'slot_feet' => 'Füße', 'slot_wrists' => 'Handgelenke', 'slot_hands' => 'Hände',
        'slot_finger1' => 'Finger 1', 'slot_finger2' => 'Finger 2', 'slot_trinket1' => 'Schmuckstück 1', 'slot_trinket2' => 'Schmuckstück 2',
        'slot_back' => 'Rücken', 'slot_mainhand' => 'Haupthand', 'slot_offhand' => 'Nebenhand', 'slot_ranged' => 'Fernkampf',
        'slot_tabard' => 'Wappenrock', 'slot_bag1' => 'Tasche 1', 'slot_bag2' => 'Tasche 2', 'slot_bag3' => 'Tasche 3', 'slot_bag4' => 'Tasche 4',
        'invalid_params' => 'Ungültige Parameter.',
        'transfer_not_found' => 'Transfer nicht gefunden.',
        'dump_unavailable' => 'Der Dump steht nicht zum Importieren zur Verfügung. Bitte den Spieler, ihn erneut zu senden.',
        'check_server_logs' => 'Überprüfe die Server-Logs.',
        'no_reason_specified' => 'Kein Grund angegeben',
        'character_not_found' => 'Charakter wurde nicht in der Datenbank gefunden.',
        'mail_subject_transfer_items' => 'Transfer-Gegenstände',
        'mail_subject_excess_items' => 'Transfer — Zusätzliche Gegenstände',
        'mail_body_excess_items' => "Diese Gegenstände passten während des Imports nicht in dein Inventar oder deine Bank.\nDu kannst sie hier abholen.",
        'label_chardump_raw' => 'Chardump',
        'item_placeholder_name' => 'Gegenstand #%d',
        'label_entry' => 'Entry',
    ],
    'ru' => [
        'stat_3' => 'Ловкость', 'stat_4' => 'Сила', 'stat_5' => 'Интеллект', 'stat_6' => 'Дух', 'stat_7' => 'Выносливость',
        'stat_12' => 'Рейтинг защиты', 'stat_13' => 'Рейтинг уклонения', 'stat_14' => 'Рейтинг парирования',
        'stat_15' => 'Рейтинг блокирования', 'stat_16' => 'Рейтинг меткости (ближний бой)',
        'stat_17' => 'Рейтинг меткости (дальний бой)', 'stat_18' => 'Рейтинг меткости заклинаний',
        'stat_19' => 'Рейтинг крит. удара (ближний бой)', 'stat_20' => 'Рейтинг крит. удара (дальний бой)',
        'stat_21' => 'Рейтинг крит. удара заклинаний', 'stat_28' => 'Рейтинг скорости (ближний бой)',
        'stat_29' => 'Рейтинг скорости (дальний бой)', 'stat_30' => 'Рейтинг скорости заклинаний',
        'stat_31' => 'Рейтинг меткости', 'stat_32' => 'Рейтинг критического удара', 'stat_35' => 'Рейтинг стойкости',
        'stat_36' => 'Рейтинг скорости', 'stat_37' => 'Рейтинг мастерства', 'stat_38' => 'Сила атаки',
        'stat_39' => 'Сила атаки (дальний бой)', 'stat_40' => 'Сила атаки в форме',
        'stat_41' => 'Целительство', 'stat_42' => 'Урон от заклинаний', 'stat_43' => 'Мана за 5 сек',
        'stat_44' => 'Пробивание брони', 'stat_45' => 'Сила заклинаний',
        'stat_46' => 'Здоровье за 5 сек', 'stat_47' => 'Пробивание заклинаний', 'stat_48' => 'Ценность блока',
        'stat_unknown' => 'Хар-ка %d',
        'dmgschool_0' => 'Физический', 'dmgschool_1' => 'Свет', 'dmgschool_2' => 'Огонь', 'dmgschool_3' => 'Природа', 'dmgschool_4' => 'Лёд', 'dmgschool_5' => 'Тень', 'dmgschool_6' => 'Тайная магия',
        'iclass_0' => 'Расходный материал', 'iclass_1' => 'Контейнер', 'iclass_2' => 'Оружие', 'iclass_3' => 'Самоцвет', 'iclass_4' => 'Броня',
        'iclass_5' => 'Ремесленный товар', 'iclass_6' => 'Метательный снаряд', 'iclass_7' => 'Реагент', 'iclass_9' => 'Рецепт',
        'iclass_11' => 'Колчан', 'iclass_12' => 'Задание', 'iclass_13' => 'Ключ', 'iclass_15' => 'Разное', 'iclass_16' => 'Знак отличия',
        'weapon_0' => 'Одноручный топор', 'weapon_1' => 'Двуручный топор', 'weapon_2' => 'Лук', 'weapon_3' => 'Огнестрельное оружие', 'weapon_4' => 'Одноручная булава',
        'weapon_5' => 'Двуручная булава', 'weapon_6' => 'Древковое оружие', 'weapon_7' => 'Одноручный меч', 'weapon_8' => 'Двуручный меч', 'weapon_10' => 'Посох',
        'weapon_13' => 'Кистевое оружие', 'weapon_15' => 'Кинжал', 'weapon_16' => 'Метательное оружие', 'weapon_18' => 'Арбалет', 'weapon_19' => 'Жезл',
        'weapon_20' => 'Удочка',
        'armorsub_0' => 'Разное', 'armorsub_1' => 'Ткань', 'armorsub_2' => 'Кожа', 'armorsub_3' => 'Кольчуга', 'armorsub_4' => 'Латы',
        'armorsub_6' => 'Щит', 'armorsub_7' => 'Манускрипт', 'armorsub_8' => 'Идол', 'armorsub_9' => 'Тотем', 'armorsub_10' => 'Печать',
        'bonding_1' => 'Привязывается при поднятии', 'bonding_2' => 'Привязывается при экипировке', 'bonding_3' => 'Привязывается при использовании',
        'bonding_4' => 'Предмет задания', 'bonding_5' => 'Предмет задания',
        'socket_color_1' => 'Мета', 'socket_color_2' => 'Красный', 'socket_color_4' => 'Жёлтый', 'socket_color_8' => 'Синий',
        'socket_color_16' => 'Оранжевый', 'socket_color_32' => 'Фиолетовый', 'socket_color_64' => 'Зелёный', 'socket_color_128' => 'Призм.',
        'socket_generic' => 'Гнездо',
        'trigger_0' => 'Использование', 'trigger_1' => 'При экипировке', 'trigger_2' => 'Шанс при ударе',
        'trigger_4' => 'Изучить заклинание', 'trigger_5' => 'Использование', 'trigger_6' => 'Изучить профессию', 'trigger_generic' => 'Триггер %d',
        'js_loading_viewer' => 'Загрузка viewer…', 'js_viewer_ok_direct' => 'Viewer OK (напрямую)',
        'js_viewer_via_proxy' => 'Viewer через прокси…', 'js_viewer_ok_proxy' => 'Viewer OK (прокси)',
        'js_loading_library' => 'Загрузка библиотеки…', 'js_rendering' => 'Рендеринг…', 'js_error_prefix' => 'Ошибка: ',
        'slot_head' => 'Голова', 'slot_neck' => 'Шея', 'slot_shoulders' => 'Плечи', 'slot_shirt' => 'Рубашка', 'slot_chest' => 'Грудь',
        'slot_waist' => 'Пояс', 'slot_legs' => 'Ноги', 'slot_feet' => 'Ступни', 'slot_wrists' => 'Запястья', 'slot_hands' => 'Руки',
        'slot_finger1' => 'Палец 1', 'slot_finger2' => 'Палец 2', 'slot_trinket1' => 'Аксессуар 1', 'slot_trinket2' => 'Аксессуар 2',
        'slot_back' => 'Спина', 'slot_mainhand' => 'Осн. рука', 'slot_offhand' => 'Доп. рука', 'slot_ranged' => 'Дальний бой',
        'slot_tabard' => 'Накидка', 'slot_bag1' => 'Сумка 1', 'slot_bag2' => 'Сумка 2', 'slot_bag3' => 'Сумка 3', 'slot_bag4' => 'Сумка 4',
        'invalid_params' => 'Неверные параметры.',
        'transfer_not_found' => 'Перенос не найден.',
        'dump_unavailable' => 'Дамп недоступен для импорта. Попросите игрока отправить его повторно.',
        'check_server_logs' => 'Проверьте логи сервера.',
        'no_reason_specified' => 'Причина не указана',
        'character_not_found' => 'Персонаж не найден в базе данных.',
        'mail_subject_transfer_items' => 'Предметы переноса',
        'mail_subject_excess_items' => 'Перенос — Дополнительные предметы',
        'mail_body_excess_items' => "Эти предметы не поместились в ваш инвентарь или банк во время импорта.\nВы можете забрать их здесь.",
        'label_chardump_raw' => 'Chardump',
        'item_placeholder_name' => 'Предмет #%d',
        'label_entry' => 'Entry',
    ],
    'pt' => [
        'stat_3' => 'Agilidade', 'stat_4' => 'Força', 'stat_5' => 'Intelecto', 'stat_6' => 'Espírito', 'stat_7' => 'Resistência',
        'stat_12' => 'Avaliação de Defesa', 'stat_13' => 'Avaliação de Esquiva', 'stat_14' => 'Avaliação de Aparar',
        'stat_15' => 'Avaliação de Bloqueio', 'stat_16' => 'Avaliação de Acerto Corpo a Corpo',
        'stat_17' => 'Avaliação de Acerto à Distância', 'stat_18' => 'Avaliação de Acerto com Feitiços',
        'stat_19' => 'Avaliação de Crítico Corpo a Corpo', 'stat_20' => 'Avaliação de Crítico à Distância',
        'stat_21' => 'Avaliação de Crítico com Feitiços', 'stat_28' => 'Avaliação de Velocidade Corpo a Corpo',
        'stat_29' => 'Avaliação de Velocidade à Distância', 'stat_30' => 'Avaliação de Velocidade com Feitiços',
        'stat_31' => 'Avaliação de Acerto', 'stat_32' => 'Avaliação de Crítico', 'stat_35' => 'Avaliação de Resiliência',
        'stat_36' => 'Avaliação de Velocidade', 'stat_37' => 'Avaliação de Perícia', 'stat_38' => 'Poder de Ataque',
        'stat_39' => 'Poder de Ataque à Distância', 'stat_40' => 'Poder de Ataque Selvagem',
        'stat_41' => 'Cura', 'stat_42' => 'Dano de Feitiços', 'stat_43' => 'Mana a cada 5 seg',
        'stat_44' => 'Penetração de Armadura', 'stat_45' => 'Poder de Feitiços',
        'stat_46' => 'Vida a cada 5 seg', 'stat_47' => 'Penetração de Feitiços', 'stat_48' => 'Valor de Bloqueio',
        'stat_unknown' => 'Stat %d',
        'dmgschool_0' => 'Físico', 'dmgschool_1' => 'Sagrado', 'dmgschool_2' => 'Fogo', 'dmgschool_3' => 'Natureza', 'dmgschool_4' => 'Gelo', 'dmgschool_5' => 'Sombra', 'dmgschool_6' => 'Arcano',
        'iclass_0' => 'Consumível', 'iclass_1' => 'Contêiner', 'iclass_2' => 'Arma', 'iclass_3' => 'Gema', 'iclass_4' => 'Armadura',
        'iclass_5' => 'Componente', 'iclass_6' => 'Projétil', 'iclass_7' => 'Reagente', 'iclass_9' => 'Receita',
        'iclass_11' => 'Aljava', 'iclass_12' => 'Missão', 'iclass_13' => 'Chave', 'iclass_15' => 'Diversos', 'iclass_16' => 'Glifo',
        'weapon_0' => 'Machado de Uma Mão', 'weapon_1' => 'Machado de Duas Mãos', 'weapon_2' => 'Arco', 'weapon_3' => 'Arma de Fogo', 'weapon_4' => 'Maça de Uma Mão',
        'weapon_5' => 'Maça de Duas Mãos', 'weapon_6' => 'Arma de Haste', 'weapon_7' => 'Espada de Uma Mão', 'weapon_8' => 'Espada de Duas Mãos', 'weapon_10' => 'Cajado',
        'weapon_13' => 'Arma de Soco', 'weapon_15' => 'Adaga', 'weapon_16' => 'Arremesso', 'weapon_18' => 'Besta', 'weapon_19' => 'Varinha',
        'weapon_20' => 'Vara de Pesca',
        'armorsub_0' => 'Diversos', 'armorsub_1' => 'Tecido', 'armorsub_2' => 'Couro', 'armorsub_3' => 'Malha', 'armorsub_4' => 'Placas',
        'armorsub_6' => 'Escudo', 'armorsub_7' => 'Panfleto', 'armorsub_8' => 'Ídolo', 'armorsub_9' => 'Totem', 'armorsub_10' => 'Sigilo',
        'bonding_1' => 'Vincula ao Pegar', 'bonding_2' => 'Vincula ao Equipar', 'bonding_3' => 'Vincula ao Usar',
        'bonding_4' => 'Item de Missão', 'bonding_5' => 'Item de Missão',
        'socket_color_1' => 'Meta', 'socket_color_2' => 'Vermelho', 'socket_color_4' => 'Amarelo', 'socket_color_8' => 'Azul',
        'socket_color_16' => 'Laranja', 'socket_color_32' => 'Roxo', 'socket_color_64' => 'Verde', 'socket_color_128' => 'Prism.',
        'socket_generic' => 'Encaixe',
        'trigger_0' => 'Usar', 'trigger_1' => 'Ao Equipar', 'trigger_2' => 'Chance ao Acertar',
        'trigger_4' => 'Aprender Feitiço', 'trigger_5' => 'Usar', 'trigger_6' => 'Aprender Profissão', 'trigger_generic' => 'Trigger %d',
        'js_loading_viewer' => 'Carregando viewer…', 'js_viewer_ok_direct' => 'Viewer OK (direto)',
        'js_viewer_via_proxy' => 'Viewer via proxy…', 'js_viewer_ok_proxy' => 'Viewer OK (proxy)',
        'js_loading_library' => 'Carregando biblioteca…', 'js_rendering' => 'Renderizando…', 'js_error_prefix' => 'Erro: ',
        'slot_head' => 'Cabeça', 'slot_neck' => 'Pescoço', 'slot_shoulders' => 'Ombros', 'slot_shirt' => 'Camisa', 'slot_chest' => 'Peito',
        'slot_waist' => 'Cintura', 'slot_legs' => 'Pernas', 'slot_feet' => 'Pés', 'slot_wrists' => 'Pulsos', 'slot_hands' => 'Mãos',
        'slot_finger1' => 'Dedo 1', 'slot_finger2' => 'Dedo 2', 'slot_trinket1' => 'Bugiganga 1', 'slot_trinket2' => 'Bugiganga 2',
        'slot_back' => 'Costas', 'slot_mainhand' => 'Mão Principal', 'slot_offhand' => 'Mão Secundária', 'slot_ranged' => 'Distância',
        'slot_tabard' => 'Tabardo', 'slot_bag1' => 'Bolsa 1', 'slot_bag2' => 'Bolsa 2', 'slot_bag3' => 'Bolsa 3', 'slot_bag4' => 'Bolsa 4',
        'invalid_params' => 'Parâmetros inválidos.',
        'transfer_not_found' => 'Transferência não encontrada.',
        'dump_unavailable' => 'O dump não está disponível para importação. Peça ao jogador para reenviá-lo.',
        'check_server_logs' => 'Verifique os logs do servidor.',
        'no_reason_specified' => 'Nenhum motivo especificado',
        'character_not_found' => 'Personagem não encontrado no banco de dados.',
        'mail_subject_transfer_items' => 'Itens da transferência',
        'mail_subject_excess_items' => 'Transferência — Itens adicionais',
        'mail_body_excess_items' => "Esses itens não couberam no seu inventário nem no banco durante a importação.\nVocê pode retirá-los aqui.",
        'label_chardump_raw' => 'Chardump',
        'item_placeholder_name' => 'Item #%d',
        'label_entry' => 'Entry',
    ],
]);

/** Idioma activo: el elegido en sesión, o DEFAULT_LANG si no eligió ninguno. */
function currentLang(): string
{
    $lang = $_SESSION['lang'] ?? DEFAULT_LANG;
    return isset(AVAILABLE_LANGS[$lang]) ? $lang : DEFAULT_LANG;
}

/**
 * Devuelve un string localizado por clave, en el idioma activo de la sesión.
 * Fallback: inglés → clave literal.
 */
function t(string $key): string
{
    global $LANG;
    $lang = currentLang();
    return $LANG[$lang][$key]
        ?? $LANG['en'][$key]
        ?? $key;
}

/**
 * Selector de idioma reutilizable — un <form> GET a set_lang.php con la
 * ruta actual como "volver a" (validada server-side, sin URLs externas).
 */
function renderLangSwitcher(): void
{
    $current = currentLang();

    $scheme = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
    $host   = $_SERVER['HTTP_HOST'] ?? '127.0.0.1:8080';
    $action = $scheme . '://' . $host . '/set_lang.php';

    $return = $_SERVER['REQUEST_URI'] ?? '/index.php';
    if (!str_starts_with($return, '/') || str_starts_with($return, '//') || str_contains($return, '://')) {
        $return = '/index.php';
    }
    ?>
    <form method="GET" action="<?= htmlspecialchars($action) ?>" class="lang-switcher">
        <input type="hidden" name="return" value="<?= htmlspecialchars($return) ?>">
        <select name="lang" onchange="this.form.submit()" aria-label="Idioma / Language">
            <?php foreach (AVAILABLE_LANGS as $code => $label): ?>
                <option value="<?= $code ?>" <?= $code === $current ? 'selected' : '' ?>>
                    <?= htmlspecialchars($label) ?>
                </option>
            <?php endforeach; ?>
        </select>
    </form>
    <?php
}








